name: Auto-refresh Google Sheets cache

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:     # Manual trigger button
  push:
    branches: [ main ]   # Also refresh on code pushes

jobs:
  update-cache:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Fetch fresh Google Sheets data
        run: node fetch-cache-data.js
      
      - name: Commit updated cache
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Show what files exist
          echo "=== Files in cache directory ==="
          ls -la public/cached-data/
          
          # Remove legacy files that shouldn't exist
          echo "=== Removing legacy files ==="
          rm -f public/cached-data/power-cache.json public/cached-data/sheets-data.json
          
          # Show git status before adding
          echo "=== Git status before adding ==="
          git status
          
          # Add all files in the directory (force add)
          echo "=== Adding files ==="
          git add -f public/cached-data/
          
          # Show what's staged
          echo "=== Staged changes ==="
          git diff --staged --name-only
          
          # Force commit all files (even if git thinks nothing changed)
          echo "=== Committing changes ==="
          git commit -m "🔄 Auto-update cached Google Sheets data [$(date +'%Y-%m-%d %H:%M:%S UTC')]" --allow-empty
          
          # Push the changes
          echo "=== Pushing to GitHub ==="
          git push
